package com.example.bubble.entities;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity
public class KeyAnswer {
    @PrimaryKey(autoGenerate = true)
    public int answerkey_id;
    public String sets_name;
    public int one;
    public int two;
    public int three;
    public int four;
    public int five;
    public int six;
    public int seven;
    public int eight;
    public int nine;
    public int ten;
    public int eleven;
    public int twelve;
    public int thirteen;
    public int fourteen;
    public int fifteen;
    public int sixteen;
    public int seventeen;
    public int eighteen;
    public int nineteen;
    public int twenty;
    public int twenty_one;
    public int twenty_two;
    public int twenty_three;
    public int twenty_four;
    public int twenty_five;
    public int twenty_six;
    public int twenty_seven;
    public int twenty_eight;
    public int twenty_nine;
    public int thirty;
    public int thirty_one;
    public int thirty_two;
    public int thirty_three;
    public int thirty_four;
    public int thirty_five;
    public int thirty_six;
    public int thirty_seven;
    public int thirty_eight;
    public int thirty_nine;
    public int forty;
    public int forty_one;
    public int forty_two;
    public int forty_three;
    public int forty_four;
    public int forty_five;
    public int forty_six;
    public int forty_seven;
    public int forty_eight;
    public int forty_nine;
    public int fifty;
    public int fifty_one;
    public int fifty_two;
    public int fifty_three;
    public int fifty_four;
    public int fifty_five;
    public int fifty_six;
    public int fifty_seven;
    public int fifty_eight;
    public int fifty_nine;
    public int sixty;
    public int sixty_one;
    public int sixty_two;
    public int sixty_three;
    public int sixty_four;
    public int sixty_five;
    public int sixty_six;
    public int sixty_seven;
    public int sixty_eight;
    public int sixty_nine;
    public int seventy;
    public int seventy_one;
    public int seventy_two;
    public int seventy_three;
    public int seventy_four;
    public int seventy_five;
}
