package com.example.bubble.entities;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity
public class KeyAnswer {
    @PrimaryKey(autoGenerate = true)
    public int answerkey_id;
    public String sets_name;
    public String one;
    public String two;
    public String three;
    public String four;
    public String five;
    public String six;
    public String seven;
    public String eight;
    public String nine;
    public String ten;
    public String eleven;
    public String twelve;
    public String thirteen;
    public String fourteen;
    public String fifteen;
    public String sixteen;
    public String seventeen;
    public String eighteen;
    public String nineteen;
    public String twenty;
    public String twenty_one;
    public String twenty_two;
    public String twenty_three;
    public String twenty_four;
    public String twenty_five;
    public String twenty_six;
    public String twenty_seven;
    public String twenty_eight;
    public String twenty_nine;
    public String thirty;
    public String thirty_one;
    public String thirty_two;
    public String thirty_three;
    public String thirty_four;
    public String thirty_five;
    public String thirty_six;
    public String thirty_seven;
    public String thirty_eight;
    public String thirty_nine;
    public String forty;
    public String forty_one;
    public String forty_two;
    public String forty_three;
    public String forty_four;
    public String forty_five;
    public String forty_six;
    public String forty_seven;
    public String forty_eight;
    public String forty_nine;
    public String fifty;
    public String fifty_one;
    public String fifty_two;
    public String fifty_three;
    public String fifty_four;
    public String fifty_five;
    public String fifty_six;
    public String fifty_seven;
    public String fifty_eight;
    public String fifty_nine;
    public String sixty;
    public String sixty_one;
    public String sixty_two;
    public String sixty_three;
    public String sixty_four;
    public String sixty_five;
    public String sixty_six;
    public String sixty_seven;
    public String sixty_eight;
    public String sixty_nine;
    public String seventy;
    public String seventy_one;
    public String seventy_two;
    public String seventy_three;
    public String seventy_four;
    public String seventy_five;

}
